/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Icon = ({ src, width, height, className, alt = "" }) => (
  <img
    src={src}
    width={width}
    height={height}
    className={className}
    alt={alt}
  />
);

export default Icon;
