/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./StartButton.module.css";

const StartButton = () => (
  <button className={styles.startButton}>
    <span className={styles.buttonText}>Start</span>
    <div className={styles.dotGroup}>
      <span className={styles.dotFilled}></span>
      <span className={styles.dotFilled}></span>
      <span className={styles.dotFilled}></span>
    </div>
  </button>
);

export default StartButton;
