/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./NavigationBar.module.css";
import Icon from "../Icon/Icon";

const NavigationBar = () => {
  const icons = [
    {
      src: "https://cdn.builder.io/api/v1/image/assets/TEMP/e7205aadb989cfcbf2a63ea506e01f5858468888669b6870c1e561e221296b5a?apiKey=05ecaddee9444e0b87f4e90bae6c22dc&&apiKey=05ecaddee9444e0b87f4e90bae6c22dc",
      width: 17,
      height: 16,
    },
    {
      src: "https://cdn.builder.io/api/v1/image/assets/TEMP/e0746c15b4ee946d681e27430900ad4ebd7c8840bb80b2e75f36e076f79c07a4?apiKey=05ecaddee9444e0b87f4e90bae6c22dc&&apiKey=05ecaddee9444e0b87f4e90bae6c22dc",
      width: 14,
      height: 21,
    },
    {
      src: "https://cdn.builder.io/api/v1/image/assets/TEMP/f7d6ee41e9d0b832af5e52cdba79cbc7f0d3b3ea76937769ededcc26b92d0f46?apiKey=05ecaddee9444e0b87f4e90bae6c22dc&&apiKey=05ecaddee9444e0b87f4e90bae6c22dc",
      width: 16,
      height: 18,
    },
    {
      src: "https://cdn.builder.io/api/v1/image/assets/TEMP/b342a59da68e167a2f85da329be9fd6c66500321ac7dc17251f18a4e409d0b8f?apiKey=05ecaddee9444e0b87f4e90bae6c22dc&&apiKey=05ecaddee9444e0b87f4e90bae6c22dc",
      width: 18,
      height: 18,
    },
    {
      src: "https://cdn.builder.io/api/v1/image/assets/TEMP/3271bce58cb1d9ab51a895f6af0e484801de0b797fdabd4183373c488d17a9b9?apiKey=05ecaddee9444e0b87f4e90bae6c22dc&&apiKey=05ecaddee9444e0b87f4e90bae6c22dc",
      width: 22,
      height: 18,
    },
    {
      src: "https://cdn.builder.io/api/v1/image/assets/TEMP/785db24d95df786452fc14f4631822da702e15901a7626147d3a87af5cd3fc3f?apiKey=05ecaddee9444e0b87f4e90bae6c22dc&&apiKey=05ecaddee9444e0b87f4e90bae6c22dc",
      width: 18,
      height: 18,
    },
    {
      src: "https://cdn.builder.io/api/v1/image/assets/TEMP/6903d9281315322101dcec1d3fff23162e3a78c2adc3087657ce6a72a24288a6?apiKey=05ecaddee9444e0b87f4e90bae6c22dc&&apiKey=05ecaddee9444e0b87f4e90bae6c22dc",
      width: 22,
      height: 22,
    },
    {
      src: "https://cdn.builder.io/api/v1/image/assets/TEMP/23f89a986397340f59b6e9d33d682e66e179cc1898f170fa6ddf4f648d46a762?apiKey=05ecaddee9444e0b87f4e90bae6c22dc&&apiKey=05ecaddee9444e0b87f4e90bae6c22dc",
      width: 22,
      height: 18,
    },
  ];

  return (
    <nav className={styles.navigationBar}>
      <div className={styles.logoGroup}>
        <img
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/ac76383b3334881041d30e563c4a6fad884ca96ba21cd03e55c702cd985604b4?apiKey=05ecaddee9444e0b87f4e90bae6c22dc&&apiKey=05ecaddee9444e0b87f4e90bae6c22dc"
          alt="Logo"
          className={styles.logo}
        />
        {icons.slice(0, 4).map((icon, index) => (
          <Icon key={index} {...icon} className={styles.icon} />
        ))}
      </div>
      <div className={styles.iconGroup}>
        {icons.slice(4, 6).map((icon, index) => (
          <Icon key={index} {...icon} className={styles.icon} />
        ))}
      </div>
      <div className={styles.iconGroup}>
        {icons.slice(6).map((icon, index) => (
          <Icon key={index} {...icon} className={styles.icon} />
        ))}
      </div>
    </nav>
  );
};

export default NavigationBar;
